version: '3.4'
# https://fluentbit.io/articles/docker-logging-elasticsearch/
# https://docs.fluentd.org/v/0.12/container-deployment/docker-compose
services:
  loggingexample:
    container_name: app
    image: ${DOCKER_REGISTRY-}loggingexample
    build:
      context: .
      dockerfile: LoggingExample/Dockerfile
    logging:
      driver: fluentd
  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    volumes:
      - ./docker-to-es.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - 24224:24224
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      - "5601:5601"
